openapi: '3.0.0'
info:
  description: Biller Management Service
  version: 1.0.0
  title: Bill Pay Exchange Biller Management API
  contact:
    name: Bill Pay Exchange Support
    email: Bill_Pay_Development_Support@mastercard.com
servers:
  - url: https://api.mastercard.com/billpay-exchange/biller-management/
tags:
  - name: biller-management-controller
    description: Biller Management Controller
paths:
  /billers:
    post:
      tags:
        - biller-management-controller
      summary: Add, edit or deactivate one or multiple Billers in Biller Pay Exchange
      operationId: processBillerUploadPostRequestUsingPOST
      requestBody:
        description: Billers to be uploaded to Biller Pay Exchange
        required: true
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/BillerManagementRequest'
            example:
              - action: Add
                effectiveDate: 04/01/2020
                general:
                  billerId: '0001234567'
                  billerLogoUrl: www.wandaauto.com
                  billerShortName: Wanda Auto
                  convenienceFee: 'Yes'
                  estimatedPostingHour: '10'
                  termsAndConditions: Terms And Conditions
                serviceRelationships:
                  - bspId: '000123'
                    serviceType: BPX_CL_EB_PAYC
                cardPaymentSupport:
                  cardEnabled: 'Yes'
                  cardNetworks:
                    - MAST
                    - VISA
                  cardTypes:
                    - CRDT
                convenienceFees:
                  - paymentType: BANK
                    flatFee: '2.0'
                    percentFee: '0.0'
                  - paymentType: CRDT
                    flatFee: '2.0'
                    percentFee: '0.0'
                serviceAreas:
                  zipCodes: "63301,63302,63303"
                consumerAuths:
                  - category: IDEN
                    categoryLabel: Iden Label
                    dataType: A
                    maxLength: '2'
                    notes: Max length 2 for IDEN category
              - action: Update
                effectiveDate: 05/01/2020
                general:
                  billerId: '0001234568'
                  billerLogoUrl: 'www.alexauto.com'
                  termsAndConditions: 'Updated Terms And Conditions'
                consumerAuths:
                  - recordAction: Add
                    category: IDEN
                    categoryLabel: Iden Label
                    dataType: A
                    maxLength: '2'
                    notes: Max length 2 for IDEN category
              - action: Deactivate
                effectiveDate: 06/01/2020
                general:
                  billerId: '0001234569'
                deactivation:
                  deactivationReasonCode: 'BCON'
                  deactivationNotes: 'Deactivate Biller 0001234568'
      responses:
        '200':
          description: 'Successfully processed the list of Billers'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BillerManagementResponse'
              example:
                - action: 'Add'
                  billerId: '0001234567'
                  statusIndicator: 'REJECTED'
                  description: 'Rejected due to validation errors, total 1 error(s) found'
                  workRequestId: null
                  effectiveDate: '04/01/2020'
                  errors:
                    - code: BPMCAPIBLR_WARN_1002
                      message: general.billerLogoUrl - Data value/format is not valid
                - action: 'Update'
                  billerId: '0001234568'
                  statusIndicator: 'SUCCESS'
                  description: 'Successfully created Biller workflow request'
                  workRequestId: '123'
                  effectiveDate: '05/01/2020'
                  errors: null
                - action: 'Deactivate'
                  billerId: '0001234569'
                  statusIndicator: 'SUCCESS'
                  description: 'Successfully created Biller deactivation workflow request'
                  workRequestId: '124'
                  effectiveDate: '06/01/2020'
                  errors: null

        '403':
          description: 'User Access Denied'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
              example:
                Errors:
                  Error:
                    - Source: Billpay Exchange Biller Management Service
                      ReasonCode: BPMCAPIBLR_ERR_0004
                      Description: User Error
                      Recoverable: true
                      Details: "Client ID 'client-id-1234567890' does not have access to manage Billers"
        '500':
          description: 'Internal Server Error, please contact Billpay Exchange Support Team'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
              example:
                Errors:
                  Error:
                    - Source: Billpay Exchange Biller Management Service
                      ReasonCode: BPMCAPIBLR_ERR_0000
                      Description: Server Error
                      Recoverable: true
                      Details: Internal Server Error
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ServerError'
              example:
                Errors:
                  Error:
                    - Source: Billpay Exchange Biller Management Service
                      ReasonCode: BPMCAPIBLR_ERR_0000
                      Description: Server Error
                      Recoverable: true
                      Details: Internal Server Error
      deprecated: false
components:
  schemas:
    BillerManagementRequest:
      type: object
      title: Biller Management Request Model
      description: Request Model class for Biller Management API
      required:
        - action
        - effectiveDate
        - general
        - serviceAreas
        - serviceRelationships
      properties:
        action:
          type: string
          description: "Biller Action, avaliable values are: Add, Update, Deactivate"
          example: 'Add'
        effectiveDate:
          type: string
          description: 'Effective Date, format MM/DD/YYYY'
          example: '04/01/2020'
        general:
          $ref: '#/components/schemas/GeneralModel'
        serviceRelationships:
          type: array
          description: 'Service Relationship List, currently only allow 1 service relationship per Biller'
          items:
            $ref: '#/components/schemas/ServiceRelationshipModel'
        cardPaymentSupport:
          $ref: '#/components/schemas/CardPaymentModel'
        convenienceFees:
          type: array
          description: 'Convenience Fee List, only required when convenience fee flag in General is set to ''Yes'''
          items:
            $ref: '#/components/schemas/ConvenienceFeeModel'
        serviceAreas:
          $ref: '#/components/schemas/ServiceAreaModel'
        consumerAuths:
          type: array
          description: 'Consumer Authentication List, maximum 3 consumer authentications allowed per Biller'
          items:
            $ref: '#/components/schemas/ConsumerAuthenticationModel'
        deactivation:
          $ref: '#/components/schemas/DeactivationModel'
    BillerManagementResponse:
      type: object
      title: Biller Management Response Model
      description: Response Model class for Biller Management API
      required:
        - action
        - description
        - effectiveDate
        - statusIndicator
      properties:
        action:
          type: string
          description: Action
        billerId:
          type: string
          description: Biller ID
        statusIndicator:
          type: string
          description: Status Indicator
        description:
          type: string
          description: Description
        workRequestId:
          type: string
          description: Biller Work Request Id
        effectiveDate:
          type: string
          description: Effective Date
        errors:
          type: array
          description: Error List
          items:
            $ref: '#/components/schemas/UserErrorModel'
    GeneralModel:
      type: object
      title: General Model
      description: Model class for Biller work request general section
      required:
        - billerId
        - billerLogoUrl
        - billerShortName
        - convenienceFee
        - estimatedPostingHour
        - termsAndConditions
      properties:
        billerId:
          type: string
          description: 'Biller Id, 10 digit numeric value'
          example: '0001234567'
        billerLogoUrl:
          type: string
          description: 'Biller Logo URL, max length 512 characters'
          example: 'www.wandaauto.com'
        billerShortName:
          type: string
          description: 'Biller ShortName, max length 35 characters'
          example: 'Wanda Auto'
        convenienceFee:
          type: string
          description: "Convenience Fee Flag, avaliable values are: Yes, No"
          example: 'Yes'
        estimatedPostingHour:
          type: string
          description: 'Estimated Posting Number, max length 2 numeric value'
          example: '10'
        termsAndConditions:
          type: string
          description: 'Terms And Conditions Text'
          example: 'Terms And Conditions'
    ServiceRelationshipModel:
      type: object
      title: Service Relationship Model
      description:  Biller Service Relationships Detail Model,
      required:
        - bspId
        - serviceType
      properties:
        recordAction:
          type: string
          description: "Record Action, avaliable values are: Add, Delete and Update, only required when Biller action is 'Update'"
          example: "Add"
        bspId:
          type: string
          description: 'BSP ID, 6 digit numeric value'
          example: '000123'
        serviceType:
          type: string
          description: "Biller Service Type, avaliable values are: BPX_CL_EB_PAYC, BPX_CL_EB, BPX_CL"
          example: 'BPX_CL_EB_PAYC'
    CardPaymentModel:
      type: object
      title: Card Payment Model
      description: Biller Card Payment Model
      required:
        - cardEnabled
        - cardNetworks
        - cardTypes
      properties:
        cardEnabled:
          type: string
          description: "Card Payment Support Flag, avaliable values are: Yes, No"
          example: 'Yes'
        cardNetworks:
          type: array
          description: "Card Networks, avaliable values are: MAST, VISA, AMEX, DSVR"
          items:
            type: string
          example: [MAST, VISA]
        cardTypes:
          type: array
          description: "Card Types, avaliable values are: CRDT, DEBT, PRPD"
          items:
            type: string
          example: [CRDT]
    ConvenienceFeeModel:
      type: object
      title: Convenience Fee Model
      description: Biller Service Area Model
      required:
        - paymentType
        - flatFee
        - percentFee
      properties:
        recordAction:
          type: string
          description: "Record Action, avaliable values are: Add, Delete and Update, only required when Biller action is 'Update'"
          example: "Add"
        paymentType:
          type: string
          description: "Payment Type, avaliable values are: CRDT, DEBT, PRPD, BANK"
          example: CRDT
        flatFee:
          type: string
          description: Flat Fee
          example: '2.0'
        percentFee:
          type: string
          description: Percent Fee
          example: '0.0'
    ServiceAreaModel:
      type: object
      title: Service Area Model
      required:
        - zipCodes
      properties:
        zipCodes:
          type: string
          description: 'Zip Codes, comma separated 5 digit numeric values'
          example: '63301, 63302, 63303'
    ConsumerAuthenticationModel:
      type: object
      title: Consumer Authentication Model
      description: Consumer Authentication Model
      required:
        - category
        - categoryLabel
        - dataType
        - maxLength
        - notes
      properties:
        recordAction:
          type: string
          description: "Record Action, avaliable values are: Add, Delete and Update, only required when Biller action is 'Update'"
          example: "Add"
        category:
          type: string
          description: "Category Code, avaliable values are: IDEN, EMAL, PHON, CODE, ADDR, OTHR"
          example: 'IDEN'
        categoryLabel:
          type: string
          description: 'Category Label, max length 128 characters'
          example: 'Iden Label'
        dataType:
          type: string
          description: "Consumer Authentication Data Type, avaliable values are: A, P, B, N, S, C, D"
          example: 'A'
        maxLength:
          type: string
          description: 'Consumer Authentication Maximum length, max length 3 numeric value'
          example: '2'
        notes:
          type: string
          description: 'Notes text, max length 1000 characters'
          example: 'Max length 2 for IDEN category'
    DeactivationModel:
      type: object
      title: Deactivation Model
      description: "Deactivation Reason and Note Model, only required when action is 'Deactivate'"
      required:
        - deactivationReasonCode
        - deactivationNotes
      properties:
        deactivationReasonCode:
          type: string
          description: "Deactivation Reason Code, avaliable values are: BCON, BMIG, LVOL, RBLR, OTHR"
          example: 'BCON'
        deactivationNotes:
          type: string
          description: 'Deactivation Note, max length 1000 characters'
          example: 'Deactiviation Notes for Wanda Auto'
    ServerError:
      type: object
      title: Server Error Model
      description: Biller Management API Server Error Model
      required:
        - Errors
      properties:
        Errors:
          type: object
          required:
            - Error
          properties:
            Error:
              type: array
              items:
                type: object
                title: Error Detail
                description: Error detail model for Biller Management API
                properties:
                  Source:
                    type: "string"
                    example: 'Billpay Exchange Biller Management Service'
                  ReasonCode:
                    type: "string"
                    example: "BPMCAPIBLR_ERR_0000"
                  Description:
                    type: "string"
                    example: "Server Error"
                  Recoverable:
                    type: "boolean"
                    example: true
                  Details:
                    type: "string"
                    example: "Internal Server Error"
    UserErrorModel:
      type: object
      title: User Error Model
      description: User Error model for validation errors
      required:
        - code
        - message
      properties:
        code:
          type: "string"
          example: 'BPMCAPIBLR_WARN_1001'
        message:
          type: "string"
          example: "general.billerId - Required field is missing"
